//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
// vovkor
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit
    {
        public int id { get; set; }

        [Display(Name = "Владелец")]
        public string owner { get; set; }
        
        [Display(Name = "Поле")]
        public string field_name { get; set; }

        [Display(Name = "Старое значение")]
        public string old_value { get; set; }
       
        [Display(Name = "Новое значение")]
        public string new_value { get; set; }
        
        [Display(Name = "Дата/Время")]
        public Nullable<System.DateTime> action_date { get; set; }

        public string Get_action_date
        {
            get { return action_date != null ? action_date.Value.ToString("dd.MM.yyyy HH:mm:ss") : String.Empty; }
        }
        public Nullable<int> acc_id { get; set; }
        public string accenumb { get; set; }
    }
}
