//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class geography
    {
        public geography()
        {
            this.maindb = new HashSet<maindb>();
            this.maindb1 = new HashSet<maindb>();
        }
    
        public int Код { get; set; }
        public Nullable<double> ORIGCTY { get; set; }
        public int GGP { get; set; }
        public string GEORUS { get; set; }
        public string FULLGEORUS { get; set; }
        public string STATUS { get; set; }
        public string CENTER_PROV_RUS { get; set; }
        public string CENTER_PROV_ENG { get; set; }
        public string ENG_GRIN { get; set; }
        public string ENG { get; set; }
        public string GEO_ENG { get; set; }
        public string LON { get; set; }
        public string LAT { get; set; }
    
        public virtual ICollection<maindb> maindb { get; set; }
        public virtual ICollection<maindb> maindb1 { get; set; }
    }
}
