//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KRIS_EXP
    {
        public KRIS_EXP()
        {
            this.maindb = new HashSet<maindb>();
        }
    
        public string NUM_EXP { get; set; }
        public string ACR { get; set; }
        public string STT { get; set; }
        public string STT_E { get; set; }
        public string REGVU { get; set; }
        public Nullable<double> GEOCOD { get; set; }
        public string COUNT_N { get; set; }
        public Nullable<double> GOD { get; set; }
        public string DAT { get; set; }
        public string NAZV { get; set; }
        public string NOTR { get; set; }
        public string OBL { get; set; }
        public string REG { get; set; }
        public string REG_E1 { get; set; }
        public string REG_E2 { get; set; }
        public string REG_E3 { get; set; }
        public string REG_E4 { get; set; }
        public string REG_E5 { get; set; }
        public string REG_E6 { get; set; }
        public string REG_E7 { get; set; }
        public string SUP { get; set; }
        public string PPL { get; set; }
        public string PPL_E { get; set; }
        public string KATEX { get; set; }
        public string SOB { get; set; }
        public string SOB_E1 { get; set; }
        public string SOB_E2 { get; set; }
        public Nullable<double> NOB { get; set; }
        public string VID { get; set; }
        public string PRM { get; set; }
        public string PRM_E { get; set; }
        public string NP { get; set; }
        public string GP { get; set; }
    
        public virtual ICollection<maindb> maindb { get; set; }
    }
}
