//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class liffom
    {
        public liffom()
        {
            this.maindb = new HashSet<maindb>();
        }
    
        public string form_code { get; set; }
        public string fullname { get; set; }
        public string loskutov_code { get; set; }
    
        public virtual ICollection<maindb> maindb { get; set; }
    }
}
