//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
// vovkor
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNet.Identity;

namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_desk
    {
        [Display(Name = "Номер")]
        public int number_request { get; set; }

        [Display(Name = "Инициатор")]
        public string author { get; set; }

        [Display(Name = "Категория")]    
        public Nullable<int> kind_id { get; set; }

        [Display(Name = "Дата открытия")]
        //[DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        //[DataType(DataType.Date)]
        public System.DateTime date_begin { get; set; }

        public string GetDateBegin
        {
            get { return date_begin.ToString("dd.MM.yyyy HH:mm:ss ") ; }
        }       

        [Display(Name = "Дата закрытия")]
        public Nullable<System.DateTime> date_end { get; set; }

        public string GetDateEnd
        {
            get { return date_end != null ? date_end.Value.ToString("dd.MM.yyyy HH:mm:ss") : String.Empty; }
        }

        [Display(Name = "Статус"), Required(ErrorMessage = "Укажите статус заявки!")]
        public int status_id { get; set; }

        [Display(Name = "Контакты для связи"), Required(ErrorMessage = "Укажите контакты для связи!")]
        public string comment { get; set; }

        [Display(Name = "Описание проблемы"), Required(ErrorMessage = "Опишите проблему!")]
        public string task { get; set; }

        [Display(Name = "Что сделано")]
        public string what_done { get; set; }

        [Display(Name = "Ответственный")]
        public string user_id { get; set; }

        [Display(Name = "ФИО инициатора"), Required(ErrorMessage = "Укажите ФИО инициатора заявки!")]
        public string fio { get; set; }

        
        public virtual sd_kind sd_kind { get; set; }
        public virtual sd_status sd_status { get; set; }
        public virtual users user { get; set; }
    }
}
