//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxonomy_crop
    {
        public taxonomy_crop()
        {
            this.botanic = new HashSet<botanic>();
        }
    
        public int id { get; set; }
        public string crop_name_eng { get; set; }
        public string crop_name_rus { get; set; }
        public string alternate_crop_name { get; set; }
        public string crop_authority { get; set; }
    
        public virtual ICollection<botanic> botanic { get; set; }
    }
}
