//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.user_roles = new HashSet<user_roles>();
            this.user_roles1 = new HashSet<user_roles>();
            this.service_desk = new HashSet<service_desk>();
        }
    
        public string username { get; set; }
        public string fio { get; set; }
    
        public virtual ICollection<user_roles> user_roles { get; set; }
        public virtual ICollection<user_roles> user_roles1 { get; set; }
        public virtual ICollection<service_desk> service_desk { get; set; }
    }
}
