//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_roles
    {
        public int id { get; set; }
        public string slave { get; set; }
        public string master { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
