//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class botanic
    {
        public botanic()
        {
            this.maindb = new HashSet<maindb>();
        }
    
        public int Code { get; set; }
        public Nullable<int> crop_code { get; set; }
        public Nullable<int> genus_code { get; set; }
        public string species { get; set; }
        public string species_author { get; set; }
        public string species_synonym { get; set; }
        public string subspecies { get; set; }
        public string subspecies_author { get; set; }
        public string grp_variety { get; set; }
        public string grp_variety_author { get; set; }
        public string variety { get; set; }
        public string variety_author { get; set; }
        public string subvariety { get; set; }
        public string subvariety_author { get; set; }
        public string forma { get; set; }
        public string forma_author { get; set; }
    
        public virtual taxonomy_crop taxonomy_crop { get; set; }
        public virtual taxonomy_genus taxonomy_genus { get; set; }
        public virtual ICollection<maindb> maindb { get; set; }
    }
}
