//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class maindb
    {
        public int id { get; set; }
        public string accenumb { get; set; }
        public string collnumb { get; set; }
        public Nullable<int> botanic_code { get; set; }
        public string accename_eng { get; set; }
        public string accename_rus { get; set; }
        public Nullable<System.DateTime> acqdate { get; set; }
        public Nullable<int> doncty { get; set; }
        public Nullable<int> oricode { get; set; }
        public string collsite_eng { get; set; }
        public string collsite_rus { get; set; }
        public Nullable<System.DateTime> colldate { get; set; }
        public string liffom { get; set; }
        public Nullable<int> sampstat { get; set; }
        public Nullable<double> dbkey { get; set; }
        public string nintrod { get; set; }
        public string nexped { get; set; }
        public string nother { get; set; }
        public string ndonor { get; set; }
        public string donor { get; set; }
        public string duplsite { get; set; }
        public Nullable<int> storage { get; set; }
        public string pedigree_rus { get; set; }
        public string pedigree_eng { get; set; }
        public string collcode { get; set; }
        public string bredcode { get; set; }
        public Nullable<float> latitude { get; set; }
        public Nullable<float> longitude { get; set; }
        public Nullable<int> elevation { get; set; }
        public Nullable<int> collsrc { get; set; }
        public string expedition { get; set; }
        public string REMARKS { get; set; }
        public bool dostupen { get; set; }
        public Nullable<System.DateTime> date_reseed { get; set; }
        public Nullable<int> owner { get; set; }
        public string owner_str { get; set; }
    
        public virtual botanic botanic { get; set; }
        public virtual collsrc collsrc1 { get; set; }
        public virtual geography geography { get; set; }
        public virtual geography geography1 { get; set; }
        public virtual INSTITUT INSTITUT { get; set; }
        public virtual INSTITUT INSTITUT1 { get; set; }
        public virtual INSTITUT INSTITUT2 { get; set; }
        public virtual KRIS_EXP KRIS_EXP { get; set; }
        public virtual liffom liffom1 { get; set; }
        public virtual sampstat_full sampstat_full { get; set; }
        public virtual storage storage1 { get; set; }
    }
}
