//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sd_status
    {
        public sd_status()
        {
            this.service_desk = new HashSet<service_desk>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<service_desk> service_desk { get; set; }
    }
}
