//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_desk
    {
        public int number_request { get; set; }
        public string author { get; set; }
        public Nullable<int> kind_id { get; set; }
        public System.DateTime date_begin { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public int status_id { get; set; }
        public string comment { get; set; }
        public string task { get; set; }
        public string what_done { get; set; }
        public string user_id { get; set; }
        public string fio { get; set; }
    
        public virtual sd_kind sd_kind { get; set; }
        public virtual sd_status sd_status { get; set; }
        public virtual users user { get; set; }
    }
}
