//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxonomy_genus
    {
        public taxonomy_genus()
        {
            this.botanic = new HashSet<botanic>();
        }
    
        public int id { get; set; }
        public string genus_name { get; set; }
        public string alternate_genus_name { get; set; }
        public string genus_authority { get; set; }
        public string subgenus_name { get; set; }
        public string alternate_subgenus_name { get; set; }
        public string subgenus_authority { get; set; }
        public string section_name { get; set; }
        public string alternate_section_name { get; set; }
        public string section_authority { get; set; }
        public string subsection_name { get; set; }
        public string alternate_subsection_name { get; set; }
        public string subsection_authority { get; set; }
        public string series_name { get; set; }
        public string alternate_series_name { get; set; }
        public string series_authority { get; set; }
        public string subseries_name { get; set; }
        public string alternate_subseries_name { get; set; }
        public string subseries_authority { get; set; }
        public Nullable<int> family_code { get; set; }
    
        public virtual ICollection<botanic> botanic { get; set; }
        public virtual taxonomy_family taxonomy_family { get; set; }
    }
}
