//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxonomy_family
    {
        public taxonomy_family()
        {
            this.taxonomy_genus = new HashSet<taxonomy_genus>();
        }
    
        public int id { get; set; }
        public string family_name { get; set; }
        public string alternate_family_name { get; set; }
        public string family_authority { get; set; }
    
        public virtual ICollection<taxonomy_genus> taxonomy_genus { get; set; }
    }
}
