//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("virdbApp2.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер образца.
        /// </summary>
        public static string accenumb {
            get {
                return ResourceManager.GetString("accenumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер образца не заполнен.
        /// </summary>
        public static string AccenumbRequired {
            get {
                return ResourceManager.GetString("AccenumbRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список образцов.
        /// </summary>
        public static string AccessionList {
            get {
                return ResourceManager.GetString("AccessionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата включения.
        /// </summary>
        public static string AcqDate {
            get {
                return ResourceManager.GetString("AcqDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните поле &quot;Дата включения в каталог&quot;.
        /// </summary>
        public static string AcqDateRequired {
            get {
                return ResourceManager.GetString("AcqDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аудит.
        /// </summary>
        public static string audit {
            get {
                return ResourceManager.GetString("audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад к списку.
        /// </summary>
        public static string Back2List {
            get {
                return ResourceManager.GetString("Back2List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Институт-селекционер.
        /// </summary>
        public static string bredcode {
            get {
                return ResourceManager.GetString("bredcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose the language.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Институт, производивший сбор.
        /// </summary>
        public static string collcode {
            get {
                return ResourceManager.GetString("collcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата сбора образца.
        /// </summary>
        public static string colldate {
            get {
                return ResourceManager.GetString("colldate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер сбора.
        /// </summary>
        public static string CollectingNumber {
            get {
                return ResourceManager.GetString("CollectingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на База данных растительных генетических ресурсов содержит 230 000 образцов.
        /// </summary>
        public static string CollectionSize {
            get {
                return ResourceManager.GetString("CollectionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Место сбора (англ.).
        /// </summary>
        public static string collsite_eng {
            get {
                return ResourceManager.GetString("collsite_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Место сбора.
        /// </summary>
        public static string collsite_rus {
            get {
                return ResourceManager.GetString("collsite_rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Источник сбора/получения.
        /// </summary>
        public static string collsrc {
            get {
                return ResourceManager.GetString("collsrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено записей:.
        /// </summary>
        public static string CountRecords {
            get {
                return ResourceManager.GetString("CountRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новый образец.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Культура.
        /// </summary>
        public static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кураторов коллекций.
        /// </summary>
        public static string curators {
            get {
                return ResourceManager.GetString("curators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коллекция.
        /// </summary>
        public static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата пересева.
        /// </summary>
        public static string date_reseed {
            get {
                return ResourceManager.GetString("date_reseed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РГР БД.
        /// </summary>
        public static string db {
            get {
                return ResourceManager.GetString("db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточка образца.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна-донор.
        /// </summary>
        public static string doncty {
            get {
                return ResourceManager.GetString("doncty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Институт-донор.
        /// </summary>
        public static string donor {
            get {
                return ResourceManager.GetString("donor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступность.
        /// </summary>
        public static string dostupen {
            get {
                return ResourceManager.GetString("dostupen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Местонахождение страховых дублетов.
        /// </summary>
        public static string duplsite {
            get {
                return ResourceManager.GetString("duplsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота места сбора.
        /// </summary>
        public static string elevation {
            get {
                return ResourceManager.GetString("elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспедиция.
        /// </summary>
        public static string expedition {
            get {
                return ResourceManager.GetString("expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широта места сбора.
        /// </summary>
        public static string latitude {
            get {
                return ResourceManager.GetString("latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип развития.
        /// </summary>
        public static string liffom {
            get {
                return ResourceManager.GetString("liffom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Долгота места сбора.
        /// </summary>
        public static string longitude {
            get {
                return ResourceManager.GetString("longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название (англ.).
        /// </summary>
        public static string NameEng {
            get {
                return ResourceManager.GetString("NameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните поле &quot;Название (англ.)&quot;.
        /// </summary>
        public static string NameEngRequired {
            get {
                return ResourceManager.GetString("NameEngRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string NameRus {
            get {
                return ResourceManager.GetString("NameRus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните поле &quot;Название&quot;.
        /// </summary>
        public static string NameRusRequired {
            get {
                return ResourceManager.GetString("NameRusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер образца, присвоенный донором.
        /// </summary>
        public static string ndonor {
            get {
                return ResourceManager.GetString("ndonor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспедиционный номер.
        /// </summary>
        public static string nexped {
            get {
                return ResourceManager.GetString("nexped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интродукционный номер.
        /// </summary>
        public static string nintrod {
            get {
                return ResourceManager.GetString("nintrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другие идентификации (номера), связанные с образцом.
        /// </summary>
        public static string nother {
            get {
                return ResourceManager.GetString("nother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна происхождения.
        /// </summary>
        public static string oricode {
            get {
                return ResourceManager.GetString("oricode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Владелец.
        /// </summary>
        public static string owner_str {
            get {
                return ResourceManager.GetString("owner_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Генеалогия (англ.).
        /// </summary>
        public static string pedigree_eng {
            get {
                return ResourceManager.GetString("pedigree_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Генеалогия.
        /// </summary>
        public static string pedigree_rus {
            get {
                return ResourceManager.GetString("pedigree_rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечания.
        /// </summary>
        public static string remarks {
            get {
                return ResourceManager.GetString("remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчёты.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Биологический статус.
        /// </summary>
        public static string sampstat {
            get {
                return ResourceManager.GetString("sampstat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Искать.
        /// </summary>
        public static string SearchNow {
            get {
                return ResourceManager.GetString("SearchNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Россия, Санкт-Петербург, ВИР.
        /// </summary>
        public static string spb {
            get {
                return ResourceManager.GetString("spb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип хранения.
        /// </summary>
        public static string storage {
            get {
                return ResourceManager.GetString("storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительную информацию о базе данных можно получить у.
        /// </summary>
        public static string SupInfo {
            get {
                return ResourceManager.GetString("SupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таксономия.
        /// </summary>
        public static string Taxonomy {
            get {
                return ResourceManager.GetString("Taxonomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните поле &quot;Таксономия&quot;.
        /// </summary>
        public static string TaxonomyRequired {
            get {
                return ResourceManager.GetString("TaxonomyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВИР.
        /// </summary>
        public static string vir {
            get {
                return ResourceManager.GetString("vir", resourceCulture);
            }
        }
    }
}
