//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
// vovkor
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNet.Identity;

namespace virdbApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sd_kind
    {
        public sd_kind()
        {
            this.service_desk = new HashSet<service_desk>();
        }

        [Display(Name = "Категория ID")]
        public int id { get; set; }

        [Display(Name = "Категория")]
        public string name { get; set; }
    
        public virtual ICollection<service_desk> service_desk { get; set; }
    }
}
